# Generated by Django 4.2.7 on 2025-08-06 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('status', models.CharField(choices=[('development', 'En Desarrollo'), ('funding', 'En Financiamiento'), ('construction', 'En Construcción'), ('operational', 'Operativo'), ('completed', 'Completado')], default='development', max_length=20, verbose_name='Estado')),
                ('total_power_installed', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potencia Total Instalada (kWp)')),
                ('total_power_projected', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potencia Total Proyectada (kWp)')),
                ('available_power', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potencia Disponible (kWp)')),
                ('price_per_wp_usd', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por Wp (USD)')),
                ('price_per_panel_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por Panel (USD)')),
                ('panel_power_wp', models.DecimalField(decimal_places=2, default=550, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potencia por Panel (Wp)')),
                ('owners', models.TextField(help_text='Separar múltiples propietarios con comas', verbose_name='Propietarios')),
                ('expected_annual_generation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Generación Anual Esperada (kWh)')),
                ('funding_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meta de Financiamiento (USD)')),
                ('funding_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Financiamiento Recaudado (USD)')),
                ('funding_deadline', models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Financiamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Proyecto Solar',
                'verbose_name_plural': 'Proyectos Solares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=projects.models.project_video_path, verbose_name='Video')),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube, Vimeo, etc.', verbose_name='URL del Video')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.solarproject')),
            ],
            options={
                'verbose_name': 'Video del Proyecto',
                'verbose_name_plural': 'Videos del Proyecto',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=projects.models.project_image_path, verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.solarproject')),
            ],
            options={
                'verbose_name': 'Imagen del Proyecto',
                'verbose_name_plural': 'Imágenes del Proyecto',
                'ordering': ['order', 'id'],
            },
        ),
    ]
