# Generated by Django 4.2.7 on 2025-08-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarproject',
            name='financial_access_password',
            field=models.CharField(default='IrisEnergia2024', help_text='Contraseña requerida para acceder a información financiera y simulador', max_length=50, verbose_name='Contraseña de Acceso Financiero'),
        ),
    ]
