# Generated by Django 4.2.7 on 2025-08-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_solarproject_financial_access_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarproject',
            name='financial_access_password',
            field=models.CharField(default='iris2025', help_text='Contraseña requerida para acceder a información financiera y simulador', max_length=50, verbose_name='Contraseña de Acceso Financiero'),
        ),
    ]
