# Generated by Django 4.2.7 on 2025-08-14 17:38

from django.db import migrations


def update_passwords_to_iris2025(apps, schema_editor):
    """Update all existing projects to use the new password 'iris2025'"""
    SolarProject = apps.get_model('projects', 'SolarProject')
    SolarProject.objects.all().update(financial_access_password='iris2025')


def reverse_update_passwords(apps, schema_editor):
    """Reverse function - update back to old password if needed"""
    SolarProject = apps.get_model('projects', 'SolarProject')
    SolarProject.objects.all().update(financial_access_password='IrisEnergia2024')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_solarproject_financial_access_password'),
    ]

    operations = [
        migrations.RunPython(update_passwords_to_iris2025, reverse_update_passwords),
    ]
