# Generated by Django 4.2.7 on 2025-08-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20250814_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarproject',
            name='commercial_whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para contacto comercial (ej: +541112345678)', max_length=20, verbose_name='WhatsApp Comercial'),
        ),
    ]
