# Generated by Django 4.2.7 on 2025-08-14 18:31

from django.db import migrations


def add_whatsapp_numbers(apps, schema_editor):
    """Add sample WhatsApp numbers for testing"""
    SolarProject = apps.get_model('projects', 'SolarProject')
    
    # Sample WhatsApp numbers for each project
    projects_data = [
        {'name': 'Techo Solar Urbano', 'whatsapp': '+5491123456789'},
        {'name': 'Solar Patagonia Wind & Sun', 'whatsapp': '+5491198765432'},
        {'name': 'Granja Solar Buenos Aires', 'whatsapp': '+5491155555555'},
        {'name': 'Solar Córdoba Comunitario', 'whatsapp': '+5491144444444'},
        {'name': 'Parque Solar Mendoza Norte', 'whatsapp': '+5491133333333'},
    ]
    
    for project_data in projects_data:
        try:
            project = SolarProject.objects.get(name=project_data['name'])
            project.commercial_whatsapp = project_data['whatsapp']
            project.save()
        except SolarProject.DoesNotExist:
            pass  # If project doesn't exist, skip it


def reverse_whatsapp_numbers(apps, schema_editor):
    """Remove WhatsApp numbers"""
    SolarProject = apps.get_model('projects', 'SolarProject')
    SolarProject.objects.all().update(commercial_whatsapp='')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_solarproject_commercial_whatsapp'),
    ]

    operations = [
        migrations.RunPython(add_whatsapp_numbers, reverse_whatsapp_numbers),
    ]
