# Generated by Django 4.2.7 on 2025-08-14 19:10

from django.db import migrations


def update_whatsapp_to_test_number(apps, schema_editor):
    """Update all projects to use the test WhatsApp number +5493517035589"""
    SolarProject = apps.get_model('projects', 'SolarProject')
    SolarProject.objects.all().update(commercial_whatsapp='+5493517035589')


def reverse_whatsapp_update(apps, schema_editor):
    """Restore previous WhatsApp numbers (optional reverse)"""
    SolarProject = apps.get_model('projects', 'SolarProject')
    
    # Restore to previous sample numbers
    projects_data = [
        {'name': 'Techo Solar Urbano', 'whatsapp': '+5491123456789'},
        {'name': 'Solar Patagonia Wind & Sun', 'whatsapp': '+5491198765432'},
        {'name': 'Granja Solar Buenos Aires', 'whatsapp': '+5491155555555'},
        {'name': 'Solar Córdoba Comunitario', 'whatsapp': '+5491144444444'},
        {'name': 'Parque Solar Mendoza Norte', 'whatsapp': '+5491133333333'},
    ]
    
    for project_data in projects_data:
        try:
            project = SolarProject.objects.get(name=project_data['name'])
            project.commercial_whatsapp = project_data['whatsapp']
            project.save()
        except SolarProject.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20250814_1531'),
    ]

    operations = [
        migrations.RunPython(update_whatsapp_to_test_number, reverse_whatsapp_update),
    ]
