# Generated by Django 4.2.7 on 2025-08-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Suscripción')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja')),
            ],
            options={
                'verbose_name': 'Suscripción a Newsletter',
                'verbose_name_plural': 'Suscripciones a Newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='WeSolar', max_length=100, verbose_name='Nombre del Sitio')),
                ('site_description', models.TextField(blank=True, verbose_name='Descripción del Sitio')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Palabras Clave SEO')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('default_annual_generation_factor', models.DecimalField(decimal_places=2, default=1500, help_text='Generación anual promedio por kWp instalado', max_digits=6, verbose_name='Factor de Generación Anual por Defecto (kWh/kWp)')),
                ('default_performance_ratio', models.DecimalField(decimal_places=3, default=0.85, help_text='Eficiencia del sistema (0.0 - 1.0)', max_digits=4, verbose_name='Ratio de Performance por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
    ]
