# Generated by Django 4.2.7 on 2025-08-22 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_auto_20250814_1610'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Acceso Concedido')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='projects.solarproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a Proyecto',
                'verbose_name_plural': 'Accesos a Proyectos',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
