# Generated by Django 4.2.7 on 2025-08-11 20:34

from django.db import migrations


def reset_data(apps, schema_editor):
    """Reset data to start fresh with new structure"""
    TariffCategory = apps.get_model('simulations', 'TariffCategory')
    InvestmentSimulation = apps.get_model('simulations', 'InvestmentSimulation')
    
    # Delete all existing data
    InvestmentSimulation.objects.all().delete()
    TariffCategory.objects.all().delete()
    
    # Create new simplified tariff categories
    categories = [
        {
            'name': 'Residencial',
            'code': 'RES',
            'description': 'Categoría para usuarios residenciales',
        },
        {
            'name': 'Comercial',
            'code': 'COM',
            'description': 'Categoría para establecimientos comerciales',
        },
        {
            'name': 'Industrial',
            'code': 'IND',
            'description': 'Categoría para instalaciones industriales',
        },
        {
            'name': 'Grandes Consumos',
            'code': 'GC',
            'description': 'Categoría para grandes consumidores de energía',
        },
    ]
    
    for cat_data in categories:
        TariffCategory.objects.create(**cat_data)


def reverse_reset_data(apps, schema_editor):
    """Reverse operation - not implemented as we don't want to restore old data"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial_new_structure'),
    ]

    operations = [
        migrations.RunPython(reset_data, reverse_reset_data),
    ]
