# Generated by Django 4.2.7 on 2025-08-22 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_reset_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ars_per_kwh', models.DecimalField(decimal_places=2, default=101.25, help_text='Precio actual de la energía eléctrica en pesos argentinos por kWh', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Energía (ARS por kWh)')),
                ('description', models.CharField(blank=True, help_text='Descripción opcional del precio (ej: "Precio promedio nacional")', max_length=200, verbose_name='Descripción')),
                ('effective_date', models.DateField(auto_now_add=True, help_text='Fecha desde la cual es efectivo este precio', verbose_name='Fecha de Vigencia')),
                ('is_active', models.BooleanField(default=True, help_text='Solo debe haber un precio activo a la vez', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Precio de Energía',
                'verbose_name_plural': 'Precios de Energía',
                'ordering': ['-effective_date'],
            },
        ),
    ]
