# Generated by Django 4.2.7 on 2025-08-22 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulations', '0002_reset_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsimulation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario autenticado (obligatorio para simulaciones persistidas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL),
        ),
    ]
