# Generated by Django 4.2.7 on 2025-08-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_add_energy_price_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyprice',
            name='effective_date',
            field=models.DateField(help_text='Fecha desde la cual es efectivo este precio', verbose_name='Fecha de Vigencia'),
        ),
    ]
