# Generated by Django 4.2.7 on 2025-08-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_investmentsimulation_user'),
        ('simulations', '0004_make_effective_date_editable'),
    ]

    operations = [
    ]
